### PR TITLE
Fix #23

### LINKED ISSUE #23: gl_showtris for VkPt
pt_showtris? Either way, same functionality. Supposedly already exists for sky surfaces, and can easily be extended. Happens to be I forgot where it resides exactly anyhow so... But it's a nice one to have around for mappers and for our own debugging reasons.

### PR DESCRIPTION
**Pull request by Admer456**
Changes:
- pt_showtris CVar
- necessary shader modifications for a global wireframe

### CODE REVIEW

**Comment by WatIsDeze** [comment]
Can we have 1 minor addition? Make sure this only happens when pt_show_sky is off? Or what?

```glsl
// Start the transparency accumulation from the primary surface emissive component, with zero alpha
	vec4 transparent = vec4(primary_emissive * throughput, 0);

    // Global wireframe
    if(global_ubo.pt_showtris != 0)
    {
        // Show edges
        if(any(lessThan(bary, vec3(0.01))))
        {
            transparent = alpha_blend(vec4(0.33,1,0.33,0.1), transparent);
        }
    }

	if(global_ubo.pt_show_sky != 0 && is_sky(ray_payload_geometry))
	{
		// show additional infor
```

**Comment by Admer456** [comment]
Why though? pt_showtris and pt_show_sky do separate things. pt_showtris shows up on all geo *except* sky faces, whereas pt_show_sky only shows a wireframe on sky faces.

**Comment by WatIsDeze** [comment]
> 
> 
> Why though? pt_showtris and pt_show_sky do separate things. pt_showtris shows up on all geo _except_ sky faces, whereas pt_show_sky only shows a wireframe on sky faces.

Can you test it out if it works properly that way? I am not nitpicking btw, just want to be sure about this new venture of ours :P

**Comment by Admer456** [comment]
Normal:
Polyhedron_2021-11-11_19-00-59

pt_showtris 1 and pt_show_sky 0
Polyhedron_2021-11-11_19-00-52

pt_showtris 1 and pt_show_sky 1
Polyhedron_2021-11-11_19-00-47

pt_showtris 0 and pt_show_sky 1
Polyhedron_2021-11-11_19-00-40

**Pull request merged**
